/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/permissions': typeof PermissionsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/permissions': typeof PermissionsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/permissions': typeof PermissionsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guest'
    | '/login'
    | '/permissions'
    | '/signup'
    | '/welcome'
    | '/admin/dashboard'
    | '/user/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guest'
    | '/login'
    | '/permissions'
    | '/signup'
    | '/welcome'
    | '/admin/dashboard'
    | '/user/dashboard'
  id:
    | '__root__'
    | '/'
    | '/guest'
    | '/login'
    | '/permissions'
    | '/signup'
    | '/welcome'
    | '/admin/dashboard'
    | '/user/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRoute: typeof GuestRoute
  LoginRoute: typeof LoginRoute
  PermissionsRoute: typeof PermissionsRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  UserDashboardRoute: typeof UserDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRoute: GuestRoute,
  LoginRoute: LoginRoute,
  PermissionsRoute: PermissionsRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  UserDashboardRoute: UserDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
